### ISSUE TITLE
Turn on discussions to have a forum for implementers and relying parties? Or just funnel implementer/RP talk to IETF mailing list?

### ISSUE THREAD

**Issue by bumblefudge** [multiformats/multibase#115]
I pulled out of my earlier PR the issue template for "expressing interest to implement" and discussing possible applications, in the interest of keeping those conversations out of Issues.  Would the implementers/core community be OK with turning on "Discussions" for this repo so that consumers of these libraries have a separate place to discuss? This would help the IETF process have a sense of who uses these outside of our field of vision, and even more usefully, a sense of who starts down the road but ends up bailing before getting anywhere 😬 

It is worth noting that while issues and PRs are part of the core git data model and carry over when repos move to, e.g.,  codeberg or gitlab, issue **templates** and discussions are github-specific and would not port.  If no one has plans to move this org and its repos to another git provider, this is a purely theoretical or ideological point, but I feel duty-bound as a decentralization and open standards guy to mention it.  

Conversely, we could just decide to use the IETF mailing list as the venue for implementer discussions, and just link to them from the readme.  I already have to watch that channel, so if I were being selfish I'd prefer this option, but I suspect we'd get slightly more intell from the additional weak signals captured here on GH from people motivated enough to comment on a discussion or fill out a discussion template, but whose feet get cold before posting to one of Ye Official IETF's mailing lists. Just a hypothesis, tho.

**Comment by rvagg** [comment]
I'm fine with this. My only hangup is email notifications which I rely on heavily to manage my queue; but I've recently become involved in a github discussion forum that seems to be sending out notifications for me that appear just like issue/pr notifications, which is neat. This would probably be a good way to capture unactionable things which would otherwise cruft up the issues list.

@vmx any objection?

**Comment by vmx** [comment]
No objections fine with me.

**Comment by rvagg** [comment]
👍 done

**Comment by ben221199** [comment]
Issue can be closed?
