### ISSUE TITLE
Remove Base256emoji

### ISSUE THREAD

**Issue by exxjob** [multiformats/multibase#117]
The prefix isn't ASCII, it doesn't conserve space or compute, it has no semiotic value, and it doesn't conform to standards.

**Comment by vmx** [comment]
Prefixes don't need to be ASCII, they are Unicode code points. Base256emoji is just an example of pushing the idea to an extreme.

**Comment by exxjob** [comment]
I know what Unicode code points are.

**Comment by exxjob** [comment]
@vmx my one liner was clear about the issue. Non-ASCII encoding isn't the issue.

**Comment by vmx** [comment]
It wasn't (and still isn't) clear to me, hence my comment about Non-ASCII.

**Comment by ben221199** [comment]
I don't understand this issue, @exxjob. The note in the README states that multibase can be encoded in different charsets, e.g., UTF-8, UTF-16 and UTF-32. All those charset are able to identify an unlimited amount of codepoints, so all emoji's are valid too.

Only problem I can imagine is the use of term "ASCII", because ASCII has a limited amount of codepoints (0-127), so has to be extended in some way, e.g. UTF-8. However, this also doesn't make the emoji-base invalid.

**Comment by rvagg** [comment]
Thanks for the feedback; but as it stands base256emoji conform to the multibase standard as it exists today. It's marked as `experimental` and probably isn't likely to change from that in the near future. We don't expect implementations to implement all of the bases listed in the table, and this one exists mainly as a tool to push at the edges of our implementations and standards and as an educational tool, not actually as something we expect to see widely used. However it is implemented in Go and JavaScript and works some of the most well deployed application stacks.

e.g. https://cloudflare-ipfs.com/ipfs/🚀🪐⭐💻😅🙅😖🌏🔴🌹😪😤🤘😟💐😝😹🐸😕😨💀💙🙊🤣😔🎤😡⚡☝💦🌎😀👈💅💚💕🏃

This may offend a sense of compactness and efficiency, but similar arguments can be made for other bases, like base2. You use in production what is most efficient for the scenario - base64 if you want compactness, base32 if you want compactness and case insensitivity, etc.

**Comment by exxjob** [comment]
@rvagg the arguments against aren't comparable to base64 or base32. I reiterate, the issue isn't non-ASCII characters, it's with the layout of base256. You can design one that meets some standard of compactness and efficiency, semiotic value, etc. Base256emoji is just a [418](https://upload.wikimedia.org/wikipedia/commons/4/45/Htcpcp_teapot.jpg), and misleading. Why have it for "educational purposes" if there is no pedagogic value...

**Comment by ben221199** [comment]
Maybe show some more examples, because I don't get it.

**Comment by vorburger** [comment]
> it is implemented in Go and JavaScript

And Java, with https://github.com/multiformats/java-multibase/pull/37
