### ISSUE TITLE
🐛 [DOC/PROCESS BUG] - Wrong Unicodes in Table?

### ISSUE THREAD

**Issue by joschua-fink** [multiformats/multibase#118]
### Description

`README.md` as well as `multibase.csv` seem to have Unicodes not matching their characters:

- base16upper has `U+0006`. I am assuming `U+0046` is meant.
- reserved character Q has `U+002F`. I am assuming `U+0051` is meant.
- Further down in `README.md` under "Reserved Terms" `Q` is mentioned with `U+0011`.

**Comment by vmx** [comment]
Thanks so much! You are absolutely right, I should've checked those myself when I reviewed it.

@bumblefudge can you please update the README and related docs?

**Comment by bumblefudge** [comment]
well that's embarassing. sehr vielen Dank for catching these, @joschua-fink !
