### ISSUE TITLE
varint

### ISSUE THREAD

**Issue by daviddias** [multiformats/multibase#12]
@jbenet could you confirm that you mean by [`<varint-base-encoding-code>`](https://github.com/multiformats/multibase#format)? A varint merged with the code itself? (high significant bit means that it requires more than one byte) How does that work for cases where the code is a specific char? @whyrusleeping is of the opinion that `varint` does not make sense in this case (see https://github.com/multiformats/go-multibase/blob/master/multibase.go)

**Comment by diasdavid** [comment]
ping @jbenet

**Comment by jbenet** [comment]
Yeah I think that was copy pasta error.

There is a problem though: what do you do to make the table infinitely
extensible? I guess the bigger constraint is the code has to be in the
right alphabet, which will be hard to satisfy both.

Given a table, matching could involve single char or multiple chars. We
just have to make sure we can have sequences that never overlap completely
(I.e. no code should be a prefix of another). We would have to be really
good at picking codes and not lock ourselves out of longer codes
accidentally...
