### ISSUE TITLE
Code table mismatch

### ISSUE THREAD

**Issue by theobat** [multiformats/multibase#15]
Hi all,

There is a mismatch between the code tables in the  [csv](https://github.com/multiformats/multibase/blob/master/multibase.csv) and the [readme](https://github.com/multiformats/multibase#multibase-table-v100-rc-semver).

More specifically we have :

| base | csv | readme |
| --- | --- | --- |
| base32 | Bb | Uu |
| base64 | m | y |
| base64url | u | Y |

Which one is authoritative ?

**Comment by Kubuxu** [comment]
//cc @jbenet

**Comment by theobat** [comment]
cc @kevina any idea ? (this is for my currently opened PR in js-multibase which -depending on this- is ready to be merged or not

**Comment by kevina** [comment]
the csv, the README need to be fixed.

**Comment by theobat** [comment]
@kevina, thanks for the answer, there's a PR live for the fix.
There's one thing I do not understand though and I think we should include an explanation for it in the readme (and/or update the input/output examples). **What does it mean when you have several letters ?** (such as 'Ff' for base 16 or 'Cc')
Is it meant to use both in the encoded output ?

**Comment by kevina** [comment]
@theobatt if there is an upper and lower case level are case letter all it means is the encoding is is case insensitive for example F2X67 or f2x67 is okay for a hex encoding of a hash.

**Comment by theobat** [comment]
Thanks @kevina, then I'm wondering which one of these approach is the best :
- case insensitive comparisons on the specific cases 
- a list of acceptable codes for each encoding

Any of these still require a default code value for the concat' operation.
The first one would require less complexity but in case we want to add distinct char as acceptable codes in the future (which seems higly unlikely though) the second one is better.

Any preference is welcome. Without answer I'll go for the first choice.

**Comment by kevina** [comment]
@jbenet will have to answer this one.
