### ISSUE TITLE
Multicodec names of multibase

### ISSUE THREAD

**Issue by Kubuxu** [multiformats/multibase#17]
My poroposal is `/multibase/$BASENAME/`
Example: `/multibase/base16/

Multicodec currently recommends `/b16/` and so on but IMO this is occupying too much of shared namespace.

**Comment by jbenet** [comment]
use `/$BASENAME`. i dont think anything else will be called `/base16` or `/base64hex` that isn't precisely those things.

**Comment by TUSF** [comment]
I agree with using a `/$BASENAME/` system. It disambiguates the system. The faq gives an apt example:

> If i give you `"1214314321432165"` is that decimal? or hex? or something else?

Similar problem is that if I give you `712516322`, am I giving you a base8 number following the multibase format, or am I giving you any other format? We have to agree prior that the multibase format is being used to begin with, which doesn't solve the proposed problem. On top of that, there's the issue of running out of encoding names that can be described in a single character.

Prefixing the encoding with the actual name is much more useful.

**Comment by matt1795** [comment]
What's the status of this? The whole idea of this thing is for it to be self describing, so adding ```/$BASENAME/```is redundant and adds confusion, whatever value follows ```multibase/``` should be of the multibase protocol, and should be able to be thrown directly into an implementer's decode function.

**Comment by vmx** [comment]
The original issue was opened when multicodec was a different concept than it is today, hence closing this one.
