### ISSUE TITLE
test vectors

### ISSUE THREAD

**Issue by jbenet** [multiformats/multibase#24]
we should have a set of test vectors for implementations

**Comment by eth-r** [comment]
My version of the haskell library has a set of test vectors for every encoding apart from unary and decimal. They are RFC-compliant where relevant, preserve leading zeros to avoid #34 and the encoding roundtrips correctly for arbitrary input values. They're available in csv format for convenience if deemed suitable for use as reference:

https://github.com/eth-r/haskell-multibase/blob/master/test1.csv
https://github.com/eth-r/haskell-multibase/blob/master/test2.csv
https://github.com/eth-r/haskell-multibase/blob/master/test3.csv
https://github.com/eth-r/haskell-multibase/blob/master/test4.csv
https://github.com/eth-r/haskell-multibase/blob/master/test5.csv

**Comment by Stebalien** [comment]
It'd probably also be a good idea to add test vectors for non-canonical encodings. For example, multibase libraries should decode `bAaAhsZLTEBwwC3TJEAqq` correctly (mixed case).

**Comment by eth-r** [comment]
Added and tested: https://github.com/eth-r/haskell-multibase/blob/master/test6.csv

**Comment by eth-r** [comment]
One notable feature of these vectors is the solution to the leading zeros problem in base58: a number of zero symbols equal to the number of leading zero bytes is prepended to the encoding of the nonzero content. This provides a clean, unambigous and space-saving solution for encodings that use division instead of mapping neatly into bytes, but is a somewhat arbitrary decision in itself and I would like comments on it. Other implemented encodings apart from base58 are not affected.

If the leading zero solution is used on base10, `\x00\x01` would encode to `901` while `\x00\xff` would encode to `90255`, `\x01\x00` to `9256`, and `\x00\x01\x00` to `90256`

**Comment by Stebalien** [comment]
Interesting. Yeah, the leading zero solution would probably make sense for all non-power-of-two bases. 

Are you interested in writing up a short base2 (and base10) spec? Nothing formal, just something unambiguous.

**Comment by eth-r** [comment]
Okay this got a bit more RFC than necessary but it should be unambiguous

### Base2

#### Encoding

A byte array (or a string represented by a byte array, eg. UTF-8) is encoded to multibase base2 by prefixing the character `0` to the encoding of the byte array in base2. The length of the multibase base2 encoding of a byte array of length _k_ is _8k+1_ bytes.

The encoding of the byte array in base2 is obtained by concatenating the base2 representations of each byte in the array, in the order the bytes are in the array.

The base2 representation of a byte is a byte array of length 8 in big-endian order, where each byte of the array is set to the character `1`, if the corresponding bit in the byte is set, and the character `0` if the corresponding bit is unset.

The character `0` means the hexadecimal value `0x30` (ASCII character `0`, decimal value 48).

The character `1` means the hexadecimal value `0x31` (ASCII character `1`, decimal value 49).

For example, the base2 representation of the ASCII character `Y`, or the hexadecimal value `0x59` is `"01011001"`. The corresponding multibase base2 encoding of the character `Y` is `"001011001"`

The base2 encoding of any byte array must not contain any other bytes apart from the characters `0` and `1`.

The entire process of encoding the byte array `[0x58, 0x59, 0x60]` is as follows:
```
map each byte to the base2 representation:
  ["01011000", "01011001", "01011010"]

concatenate:
  "010110000101100101011010"

prefix with '0':
  "0010110000101100101011010"
```
#### Decoding

The canonical format of multibase base2 encoding is decoded by dropping the first byte (which must be the character `0`), dividing the remaining byte array to _k_ sections of length _8_, and mapping to each byte in an output buffer of _k_ bytes the binary value of the corresponding section.

The binary value of a byte section is obtained by taking the bytes of the section in big-endian order, and setting the corresponding bit in the output byte if the byte is `1`, and leaving the bit unset if `0`.

For example, the binary value of the byte section `"00110111"` is `0x37`.

The process, with input `"00100000101000010"`:
```
drop the leading zero:
  "0100000101000010"
divide to sections:
  ["01000001", "01000010"]
allocate output buffer:
  [0x00, 0x00]
set the correct bits:
  [0x41, 0x42] or "AB"
```

A non-canonical encoding of multibase base2 whose length is not equal to _8k+1_ for some _k_, may be decoded by dropping the first byte, and then prefixing to the encoding the smallest number of bytes that makes the length of the encoding be canonical, and then decoding it as if it were in the canonical base2 form. For example, the non-canonical encoding `"011010"` may be decoded like the canonical base2 encoding `"000" + "11010"` to get `0x1a`. A standard multibase implementation must not produce non-canonical encoding.

**Comment by eth-r** [comment]
### Base10

#### Encoding

A byte array is encoded to multibase base10 by prefixing its base10 encoding with the character `9`.

A byte array is encoded to base10 by concatenating its leading zeros with the ASCII encoding of the decimal representation of the byte array interpreted as a big-endian integer.

The leading zeros of a byte array are a byte array of the character `0`, whose length is equal to the length of consecutive `0x00` bytes in the beginning of the byte array.

The decimal representation of a byte array is obtained by setting the accumulator to the value of the first nonzero byte of the array, and then for every subsequent byte setting a new value for the accumulator to be equal to the previous value multiplied by 256, plus the value of the current byte. The last byte of the output array is set to the ASCII character corresponding to the value of the accumulator modulo 10, and the accumulator is set to the accumulator divided by 10. The second-to-last byte of the output array is then set with the same process, iterating until the accumulator is 0.

The multibase base10 encoding of a byte array must not contain any characters outside the range `0..9` (decimal 48..57; hexadecimal `0x30..0x39`)

The multibase base10 encoding of the byte array `[0x00, 0x01]` is `"901"`

The encoding of `[0x00, 0x00, 0xff]` is `"900255"`

The encoding of `[0x01, 0x00]` is `"9256"`

The encoding of `[0x00, 0x01, 0x00]` is `"90256"`

#### Decoding

A multibase base10 encoding is decoded by dropping its first byte (which must be the character `9`)

A base10 encoding is decoded into a byte array by concatenating its leading null bytes with the big-endian representation of the encoding interpreted as a decimal integer.

The leading null bytes of a base10 encoding are a byte array of `0x00` whose length is equal to the number of `0` characters before a nonzero character in the base10 encoding.

The big-endian representation of a base10 encoding is obtained by setting the accumulator to the number corresponding to the first nonzero ASCII numeral in the encoding, then for each subsequent character multiplying the accumulator by 10 and adding to it the number corresponding to the character.

The number corresponding to a character in the range `0..9` is obtained by subtracting the decimal value 48 (hexadecimal `0x30`) from the value of the byte. The character corresponding to a decimal number is obtained by adding 48 to the number.

**Comment by eth-r** [comment]
The test vectors now include base10 as well.

**Comment by Stebalien** [comment]
This is awesome! Mind making a PR with these RFCs (put them in an `rfcs` directory, we should also put the other rfcs there as well) and a separate one with the test vectors (in a `tests` directory)?

Also, if I don't respond quickely, try hitting me up on IRC (stebalien on irc.freenode.net, usually on the #ipfs-dev channel). My email is a bit overloaded at the moment so I'm missing github notifications.

**Comment by eth-r** [comment]
Done
