### ISSUE TITLE
Haskell implementation for multibases.

### ISSUE THREAD

**Issue by Unlambder** [multiformats/multibase#29]
Hello,
I would be interested in developping a multibase format in haskell, I've read the contributing doc but i still have a few questions :  - is anyone working on this already or can i go for it? -i'm still pretty new to github, do, i directly pull the multiformats repo or do I have to submit the code for checking first?

I hope i can be useful to this project and even though i lack experience i'm here to learn so don't hesitate to reject my code if its not good enough.

**Comment by diasdavid** [comment]
Hi @Unlambder, first of all, welcome! 

Yes, we would really appreciate help with the Haskell implementation, right now we only have [multibase in these languages](https://github.com/multiformats?utf8=%E2%9C%93&q=multibase&type=&language=).

Don't be afraid of giving it a try and you can learn from the [multihash implementation in Haskell](https://github.com/multiformats/haskell-multihash) in how it was done.

Let us know if you have questions!

**Comment by Unlambder** [comment]
Thank you @diasdavid , i am currently making progress but i try to implement many things myself and use as few imports as possible so it could take a while (nearly finished the encoding part).

**Comment by Unlambder** [comment]
Hello, I have a nearly finished working implementation https://github.com/Unlambder/haskell-multibase but i don't know how i can transfer it to multiformats , can anyone tell me how it's done?

**Comment by diasdavid** [comment]
@Unlambder I just added you to the team https://github.com/orgs/multiformats/teams/haskell-team/members, once you accept you should be able to transfer in the `Settings` page of the repo :)

**Comment by Unlambder** [comment]
Nice! thanks for helping me, I'll close this issue and keep on developping the implementation in its repo.
