### ISSUE TITLE
Clarifying the varint nature of multibase codecs

### ISSUE THREAD

**Issue by vmx** [multiformats/multibase#43]
This is a follow-up on https://github.com/multiformats/multicodec/issues/89 (I didn't want to side-track that issue).

Issue #12 seems to be related.

From the multibase spec:

>The Format is:
>
> ```
> <varint-base-encoding-code><base-encoded-data>
> ```

So the first few bytes are a [multiformats varint](https://github.com/multiformats/unsigned-varint).

But according to https://github.com/multiformats/multicodec/issues/89#issuecomment-439240654, the multibase encoding table is about characters (or Symbols as @Stebalien names them). This means that they depend on the string encoding. An `f`, which stands for base16, encoded as UTF-8/ASCII is `0x66` as hex (`102` decimal) which qualifies as a varint.

But if you you encode `f` as UTF-32, it's byte sequence as decimals is `[255, 254, 0, 0, 102, 0, 0, 0]` which clearly isn't a varint.

I propose changing the spec to something like:

>The format is:
>
> ```
> <string-encoded-identifier><base-encoded-data>
> ```
>
> Multibases are always strings with a certain character encoding, usually UTF-8. The `<string-encoded-identifier>` is a sequence of characters (currently only a single one) according to the multibase table. If the string is encoded as UTF-8 the sequence of the characters of the `<string-encoded-identifier>` can be interpreted as a  [multiformats varint](https://github.com/multiformats/unsigned-varint). This way it can be determined where the `<string-encoded-identifier>` stops and the actual base encoded data starts.

/cc  @fluency03 @Stebalien

**Comment by Stebalien** [comment]
That's... nonsensical, thanks for pointing this out. This should say "symbol", "z" means base58 in any encoding.

**Comment by vmx** [comment]
@Stebalien This means that the `<multibase-encoding-symbol>` will always only be a single character. Isn't this opposed to the future-proofness we have in other multiformats?

If it really is a single character only, could we rename it from `symbol` to `character`? I think it would make things clearer.

**Comment by vmx** [comment]
@Stebalien Sorry I didn't see the open PR, just the `remove mentions of varint` commit linked and clicked on it. I thought it was already merged. I'll put further comments on the PR.
