### ISSUE TITLE
Ruby implementation of multibase

### ISSUE THREAD

**Issue by SleeplessByte** [multiformats/multibase#53]
Following the format of #29 

I would be interested in developing a `multibase` implementation in `ruby`. I've read the [contributing document](https://github.com/multiformats/multiformats/blob/master/contributing.md). I have a WIP implementation at [SleeplessByte/ruby-multibase](https://github.com/SleeplessByte/ruby-multibase).

What other steps do I have to take?

**Comment by SleeplessByte** [comment]
It's now done and passes the spec.

**Comment by Stebalien** [comment]
Thanks!
