### ISSUE TITLE
Module used for base encoding is not compliant with RFC3548

### ISSUE THREAD

**Issue by daviddias** [multiformats/multibase#75]
Folks, saw this today:

![image](https://user-images.githubusercontent.com/1211152/92682052-42e80f00-f327-11ea-8a53-c696882c8497.png)

https://www.npmjs.com/package/base-x

This is rather concerning. However, it is unclear in what bits it is not compliant. Has anyone checked this to ensure that multibase is using something that will lead to the same base encodings as everyone else?

**Comment by vmx** [comment]
@daviddias This issue should've been opened at https://github.com/multiformats/js-multibase/ as it only concerns the JS implementation.

RFC3548 is obsoleted by RFC4648. If you look at the source directory you can find [a file called rfc4648.js](https://github.com/multiformats/js-multibase/blob/424709195b46ffb1d6f2f69a7707598ebe751e5e/src/rfc4648.js), which is exactly for those cases.

This repo also contains [test vectors](https://github.com/multiformats/multibase/tree/ae81809e22f9c8d8396e96b83c8bdae687a00c70/tests) to make sure things works across implementations. Those test vectors are currently used at least by the JS and Rust implementations.
