### ISSUE TITLE
Consistancy of numeral prefixes

### ISSUE THREAD

**Issue by ben221199** [multiformats/multibase#87]
When looking at the numeral prefixes, it appears to me that there isn't a full consistancy. This happens because the prefix for base2 is `0` and not `1`.

| Base | Current prefix | Consistant prefix | Consistant? |
| -- | -- | -- | -- |
| 1 | 1 | 0 | NO, but removed from the spec |
| 2 | 0 | 1 | NO |
| 3 | - | 2 | (not used) |
| 4 | - | 3 | (not used) |
| 5 | - | 4 | (not used) |
| 6 | - | 5 | (not used) |
| 7 | - | 6 | (not used) |
| 8 | 7 | 7 | YES |
| 9 | - | 8 | (not used) |
| 10 | 9 | 9 | YES |
| 11 | - | A/a | (not used) |
| 12 | - | B/b | NO (used by `base32`, but I think that is fine) |
| 13 | - | C/c | NO (used by `base32pad`, but I think that is fine) |
| 14 | - | D/d | (not used) |
| 15 | - | E/e | (not used) |
| 16 | F/f | F/f | YES |

The table above shows what I mean. The bases having `NO` have some inconsistancy.

**Comment by vmx** [comment]
Choosing the prefixes predates my involvement is this project, but I think the prefixes don't really follow a certain rule, they were arbitrarily chosen.
